#!/usr/bin/sh

### BEGIN INIT INFO
# Provides:          hiawatha httpd httpd-cgi
# Required-Start:    $syslog $network $remote_fs
# Required-Stop:     $syslog $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Hiawatha webserver
# Description:       Hiawatha, a secure and advanced webserver.
### END INIT INFO

# /etc/init.d/hiawatha: start and stop the Hiawatha webserver daemon
NAME=Hiawatha
DAEMON=/usr/sbin/hiawatha
WIGWAM=/usr/sbin/wigwam
PIDFILE=/var/run/hiawatha.pid

start() {
	[ -x $DAEMON ] || exit 5

	umask 077

	if [ -f $PIDFILE ]; then
		echo $NAME is already running.
		return 1
	fi

	echo "Starting Hiawatha webserver."
	$WIGWAM -q || return
	$DAEMON
}

stop() {
	if [ ! -f $PIDFILE ]; then
		echo $NAME is not running.
		return 1
	fi

	echo "Shutting down Hiawatha webserver."
	kill -15 `cat $PIDFILE`
	rm -f $PIDFILE
}

status() {
	if [ -f $PIDFILE ]; then
		echo $NAME is running.
	else
		echo $NAME is not running.
	fi
}

restart() {
	stop
	sleep 3
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	status)
		status
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 3
esac

exit $?
